# site
title: Thoughts | Joe McAlister
baseurl: "/"
url: "http://thoughts.joe.ac"
favicon: "/assets/sample/ico.png"
g_analytics: UA-12345678-1

# bio
header: Joe's Thoughts and Research
desc: >
  Thoughts and rambles as I develop artwork and explore new approaches. 
  Occasionally technical, sometimes arty usually overly detailed.

# posts
date_format: "%F"
post_title: Post
post_date: Date
post_cat: Type

# post detail
prev-next: true

# build settings
markdown: kramdown
# theme: louie
remote_theme: lllychen/louie
exclude:
  - Gemfile
  - Gemfile.lock
